parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: festival
    database_user: root
    database_password: devdb
    database_charset:  UTF8
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 658047c7cbcb9cfdb84e945ab734b7050687270a
    database_path: null
